import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { JetBrains_Mono } from 'next/font/google';
import { ToastProvider } from "@/components/ToastProvider";

const mono = JetBrains_Mono({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* =========================
   DASHBOARD STATS DATA
   - This is the data source for the top summary cards
   - Each property feeds one card
   - Later, this can come from your backend
========================= */
const dashboardStats = {
  firms: 1,
  funds: 1,
  investors: 1,
  investorAccounts: 1,
  pendingSubscriptions: 1,
  pendingRedemptions: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`min-h-full flex flex-col ${mono.className}`}>
        <ToastProvider>{children}</ToastProvider>
        </body>
    </html>
  );
}
